### ISSUE TITLE
Hi, can I get the wifi data that you collected?

### ISSUE THREAD

**Issue by JayC1208** [cod3monk/showfloor-heatmap#1]
Hi, I checked your github repo and I cannot find the data from SC 17 (or at least SC 19)

It said that I can find data in github or at http://monitor.sc17.org/showfloor-heatmap/index_traffic.html according to 
https://blog.sflow.com/2017/11/real-time-wifi-heat-map.html this web page..
The monitor webpage is not working and I cannot find the dataset. 

Is there any way that I can get the data you've collected?

thanks

**Comment by cod3monk** [comment]
We never published the data, other than through the used API during the conference. There is also no public archive of the generated json objects.

The http://monitor.sc17.org/showfloor-heatmap/index_traffic.html page was only available for a live view during the conference. It ran a copy of this repository with live data being translated from the Cisco Prime appliance into a simplified json format.

Hope this helped :)

**Comment by JayC1208** [comment]
Thanks for reply!!
